# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [7]:
# import libraries
import numpy as np
import torch

# Using numpy

In [8]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-1.92 -2.68 -0.73 -1.8   4.43]
 [ 0.02  4.29  8.68 -7.38 -6.19]
 [-0.52 -1.87 -0.39  0.63  2.27]]
 
[[-0.68 -0.69 -1.23 -0.12]
 [ 4.37  2.77 -0.31  3.51]
 [ 0.74  0.3  -4.3  -1.74]
 [ 3.53  2.4   0.11  2.24]
 [-3.66 -2.34  3.5  -0.37]
 [ 2.81  1.7  -8.1  -3.37]
 [ 0.25  0.24  0.86  0.44]]


# Using pytorch

In [12]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.7500,  1.2300, -1.5000,  0.4300, -0.2900, -0.2600,  1.1800],
        [ 0.0100,  0.0000,  0.8400, -0.7400, -0.9700, -0.1200, -2.0700],
        [-1.8100, -1.5000,  3.8200, -1.1000,  2.8000, -1.5800, -1.7600]],
       dtype=torch.float64)
 
tensor([[ 0.7500,  1.2300, -1.5000,  0.4300, -0.2900, -0.2600,  1.1800],
        [ 0.0100,  0.0000,  0.8400, -0.7400, -0.9700, -0.1200, -2.0700],
        [-1.8100, -1.5000,  3.8200, -1.1000,  2.8000, -1.5800, -1.7600]])


In [16]:
D = A@C1
print(type(D))
print(D)
E = np.round( D  ,2)
print(type(E))
print(E)

<class 'torch.Tensor'>
tensor([[ 7.5128e-01,  1.2288e+00, -1.5034e+00,  4.2518e-01, -2.9468e-01,
         -2.6069e-01,  1.1806e+00],
        [ 1.3743e-02,  3.0230e-03,  8.3530e-01, -7.4360e-01, -9.6595e-01,
         -1.2315e-01, -2.0704e+00],
        [-1.8146e+00, -1.4965e+00,  3.8217e+00, -1.0976e+00,  2.8030e+00,
         -1.5801e+00, -1.7564e+00]], dtype=torch.float64)
<class 'torch.Tensor'>
tensor([[ 0.7500,  1.2300, -1.5000,  0.4300, -0.2900, -0.2600,  1.1800],
        [ 0.0100,  0.0000,  0.8400, -0.7400, -0.9700, -0.1200, -2.0700],
        [-1.8100, -1.5000,  3.8200, -1.1000,  2.8000, -1.5800, -1.7600]],
       dtype=torch.float64)


In [21]:
F = np.round(E*E,2)
print(F)
print(type(F))

tensor([[5.6000e-01, 1.5100e+00, 2.2500e+00, 1.8000e-01, 8.0000e-02, 7.0000e-02,
         1.3900e+00],
        [0.0000e+00, 0.0000e+00, 7.1000e-01, 5.5000e-01, 9.4000e-01, 1.0000e-02,
         4.2800e+00],
        [3.2800e+00, 2.2500e+00, 1.4590e+01, 1.2100e+00, 7.8400e+00, 2.5000e+00,
         3.1000e+00]], dtype=torch.float64)
<class 'torch.Tensor'>


In [24]:
G = np.round(E@E.T,2)
print(G)
print(type(G))

tensor([[  6.0500,  -3.7000, -11.8800],
        [ -3.7000,   6.4900,   5.1200],
        [-11.8800,   5.1200,  34.7600]], dtype=torch.float64)
<class 'torch.Tensor'>
