# COURSE: A deep understanding of deep learning
## SECTION: Data matrices and loaders
### LECTURE: Anatomy of a torch dataset and dataloader
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [72]:
# import libraries
import numpy as np
import torch
from torch.utils.data import DataLoader,TensorDataset

# Datasets

In [73]:
# create some data in numpy

nObservations = 100
nFeatures = 20

data = np.random.randn(nObservations,nFeatures)

In [74]:
# Convert to pytorch tensor
dataT = torch.tensor( data ) 

# print out some information
print('Numpy data:')
print(type(data))
print(data.shape) # numpy -> .shape
print(data.dtype)
print(' ')

print('Tensor data:')
print(type(dataT))
print(dataT.size()) # torch -> .size()
print(dataT.dtype)
print(' ')

Numpy data:
<class 'numpy.ndarray'>
(100, 20)
float64
 
Tensor data:
<class 'torch.Tensor'>
torch.Size([100, 20])
torch.float64
 


In [75]:
# Sometimes you need to convert data types

dataT2 = torch.tensor( data ).float()
print(dataT2.dtype)

# "long" is for ints
dataT3 = torch.tensor( data ).long()
print(dataT3.dtype)

print(dataT2.size())
print(dataT3.size())

torch.float32
torch.int64
torch.Size([100, 20])
torch.Size([100, 20])


In [76]:
# Convert tensor into PyTorch Datasets

# dataset = TensorDataset(data) # not a tensor!
dataset = TensorDataset(dataT)

print(type(dataset.tensors))
# dataset is a two-element tuple comprising data,labels
# dataset.tensors[0]

<class 'tuple'>


In [77]:
# Let's try again with labels
labels = torch.ceil(torch.linspace(.01,4,nObservations))



# # transform to an actual matrix (column vector)
labels = labels.reshape(( len(labels),1 ))
# print( labels )

# # now make another dataset
dataset = TensorDataset(dataT,labels)
print( dataset.tensors[0].size() )
print( dataset.tensors[1].size() )

# # for comparison
print( np.shape(np.random.randint(5,size=nObservations)) )

torch.Size([100, 20])
torch.Size([100, 1])
(100,)


# DataLoaders

In [78]:
# create a dataloader object
batchsize = 25
dataloader = DataLoader(dataset,batch_size=batchsize)#,shuffle=True,drop_last=True)
dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [79]:
# sizes of each batch
for dat,labs in dataloader:
  print('BATCH INFO:')
  print(dat.size())
  print(labs.size())
  print(' ')

BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 


In [80]:
# inspect the labels
for dat,labs in dataloader:
  print(labs.T)
  print(' ')

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
 
tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.]])
 
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3.]])
 
tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4., 4., 4., 4., 4., 4.]])
 


In [81]:
# try again with shuffling (shuffling happens during iterations)
dataloader = DataLoader(dataset,batch_size=batchsize,shuffle=True)

for dat,labs in dataloader:
  print(labs.T)
  print(' ')

tensor([[3., 4., 4., 2., 4., 1., 4., 2., 1., 2., 3., 3., 1., 4., 2., 3., 3., 1.,
         4., 2., 1., 4., 2., 2., 2.]])
 
tensor([[3., 3., 1., 4., 1., 2., 2., 2., 1., 1., 4., 1., 4., 2., 4., 2., 3., 2.,
         1., 1., 2., 2., 1., 2., 2.]])
 
tensor([[4., 4., 2., 4., 1., 3., 4., 2., 3., 4., 3., 3., 3., 1., 3., 1., 4., 2.,
         4., 1., 3., 3., 2., 4., 3.]])
 
tensor([[3., 4., 3., 3., 1., 3., 2., 3., 1., 1., 4., 4., 3., 2., 1., 4., 2., 4.,
         3., 1., 4., 1., 3., 1., 1.]])
 


In [82]:
# To get only one batch (e.g., for testing)
dat,labs = next(iter(dataloader))
labs

tensor([[1.],
        [1.],
        [4.],
        [4.],
        [2.],
        [3.],
        [4.],
        [4.],
        [3.],
        [4.],
        [1.],
        [4.],
        [2.],
        [2.],
        [1.],
        [3.],
        [2.],
        [2.],
        [1.],
        [3.],
        [4.],
        [1.],
        [2.],
        [2.],
        [1.]])