# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [4]:
widenet.cuda

<bound method Module.cuda of Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)>

# Peeking inside the network

In [5]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')
    
(0): Linear(in_features=2, out_features=2, bias=True)
(1): Linear(in_features=2, out_features=2, bias=True)
(2): Linear(in_features=2, out_features=3, bias=True)

('0.weight', Parameter containing:
tensor([[ 0.0010, -0.3575],
        [ 0.1366, -0.3163]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.4937, -0.6975], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.5271,  0.5254],
        [ 0.5537,  0.0450]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([ 0.0100, -0.0221], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.7057,  0.3352],
        [ 0.4002,  0.0036],
        [-0.3781,  0.5865]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.4630, -0.0332, -0.4478], requires_grad=True))
 


In [6]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [7]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[ 0.6936,  0.3922],
        [-0.3485,  0.2734],
        [-0.6545,  0.4136],
        [ 0.0471, -0.0920]], requires_grad=True)
 
Parameter containing:
tensor([-0.5906, -0.2036,  0.5843,  0.0126], requires_grad=True)
 
Parameter containing:
tensor([[ 0.3895,  0.4418,  0.3062, -0.2680],
        [ 0.2772, -0.0127,  0.2372, -0.2058],
        [-0.4702,  0.2326, -0.1019, -0.1615]], requires_grad=True)
 
Parameter containing:
tensor([-0.0889,  0.1065, -0.2630], requires_grad=True)
 


In [8]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [9]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [11]:
pip install torchsummary

Note: you may need to restart the kernel to use updated packages.


In [13]:

# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))
summary(deepnet,(1,2))
### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 2]               6
            Linear-2                 [-1, 1, 2]               6
            Linear-3                 [-1, 1, 3]               9
Total params: 21
Trainable params: 21
Non-trainable params: 0
-----------------------------------------------------